"""remove pk from ticket table

Revision ID: 0fdf41446f48
Revises: bb3c44f5a058
Create Date: 2023-03-28 13:59:51.759210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0fdf41446f48'
down_revision = 'bb3c44f5a058'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ticket_pk_key', 'ticket', type_='unique')
    op.drop_column('ticket', 'pk')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ticket', sa.Column('pk', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_unique_constraint('ticket_pk_key', 'ticket', ['pk'])
    # ### end Alembic commands ###
